### ISSUE TITLE
RangeError: Invalid status code: 0

### ISSUE THREAD

**Issue by retorillo** [retorillo/pubdir#8]
```
RangeError: Invalid status code: 0
    at ServerResponse.writeHead (_http_server.js:192:11)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:571:10)
    at res.sendFile.err (***\bin\pubdir.js:171:32)
    at ***\node_modules\express\lib\response.js:413:22
    at onaborted (***\node_modules\express\lib\response.js:975:5)
    at Immediate.<anonymous> (***\node_modules\express\lib\response.js:1015:9)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by retorillo** [comment]
Check whether err.code is `ECONNABORTED`

``` javascript
function onaborted() {
    if (done) return;
    done = true;

    var err = new Error('Request aborted');
    err.code = 'ECONNABORTED';
    callback(err);
}
```

https://github.com/expressjs/express/blob/9375a9afa9d7baa814b454c7a6818a7471aaef00/lib/response.js#L974
